#!/usr/bin/env bash
# Install and configure nginx on a new Ubuntu machine

# Install nginx
apt-get update
apt-get install -y nginx

# Allow HTTP traffic
ufw allow 'Nginx HTTP'

# Create default page with required content
echo "Holberton School" > /var/www/html/index.html

# Configure nginx default site
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Create symbolic link if not exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Ensure nginx is running
service nginx restart
